import { Palette } from "../theme/globals.slint";
import { WindowShell, CustomBtn } from "../components/window-shell.slint";
import { LineEdit /*, ScrollView */} from "std-widgets.slint";

import { MapaKanwa, MapPoint } from "../components/mapa-kanwa.slint";
import { MapaKokpit } from "../components/mapa-kokpit.slint";

export { MapPoint } 

export component GenetekaCoJestWindow inherits WindowShell {
    preferred-width: 600px;
    preferred-height: 600px;
    window-title: "GENETEKA - CO JEST?";
    callback search(string);
    in property <[MapPoint]> map_points: [];
    in-out property <[string]> search_results: [];
    VerticalLayout {
        padding: 20px;
        spacing: 15px;
        HorizontalLayout {
            spacing: 10px;
            height: 40px;
            input := LineEdit {
                placeholder-text: "Szukaj parafii...";
                accepted => {
                    root.search(self.text);
                }
            }

            CustomBtn {
                text: "SZUKAJ";
                width: 100px;
                primary: true;
                clicked => {
                    root.search(input.text);
                }
            }
        }

        kanwa := MapaKanwa {
            map_points: root.map_points;
            MapaKokpit {
                // TUTAJ ZMIENIASZ POZYCJĘ ("nw", "ne", "sw", "se")
                anchor: "sw";
                margin: 10px;

                // POPRAWKA: Tutaj "parent" to mapa, więc możemy bez problemu liczyć pozycję!
                x: (self.anchor == "nw" || self.anchor == "sw") ? self.margin : parent.width - self.preferred-width - self.margin;
                y: (self.anchor == "nw" || self.anchor == "ne") ? self.margin : parent.height - self.preferred-height - self.margin;
                zoom_in => {
                    kanwa.zoom_around_center(kanwa.map_zoom + 0.5);
                }
                zoom_out => {
                    kanwa.zoom_around_center(kanwa.map_zoom - 0.5);
                }
                pan(dx, dy) => {
                    kanwa.map_offset_x += dx;
                    kanwa.map_offset_y += dy;
                }
                reset => {
                    kanwa.map_zoom = 1.0;
                    kanwa.map_offset_x = 0px;
                    kanwa.map_offset_y = 0px;
                }
            }
        }
        // ----------------------------------------

        //Rectangle {
        //    background: Palette.background-light;
        //    border-radius: 4px;
        //    vertical-stretch: 1;
        //    clip: true;
        //    ScrollView {
        //        viewport-width: self.width;
        //        VerticalLayout {
        //            padding: 10px;
        //            spacing: 5px;
        //            for res in root.search_results: Text {
        //                text: res;
        //                color: Palette.accent-success;
        //                font-family: "Fira Code";
        //            }
        //        }
        //    }
        //}
    }
}
