import { Palette } from "../theme/globals.slint";
import {
    WindowShell,
    WindowCtrl,
    CustomBtn,
} from "../components/window-shell.slint";
import { LineEdit, ScrollView } from "std-widgets.slint";


export component GenetekaCoJestWindow inherits WindowShell {
    preferred-width: 600px;
    preferred-height: 800px;
    window-title: "GENETEKA - CO JEST?";

    
    // Właściwości i callbacki dla Rusta
    callback search(string);
    in-out property <[string]> search_results: [];
    VerticalLayout {
        padding: 20px;
        spacing: 15px;
        HorizontalLayout {
            spacing: 10px;
            height: 40px;
            input := LineEdit {
                placeholder-text: "Szukaj parafii...";
                accepted => {
                    root.search(self.text);
                }
            }

            CustomBtn {
                text: "SZUKAJ";
                width: 100px;
                primary: true;
                clicked => {
                    root.search(input.text);
                }
            }
        }

        Rectangle {
            background: Palette.background-light;
            border-radius: 4px;
            vertical-stretch: 1;
            clip: true;
            ScrollView {
                viewport-width: self.width;
                VerticalLayout {
                    padding: 10px;
                    spacing: 5px;
                    for res in root.search_results: Text {
                        text: res;
                        color: Palette.accent-success;
                        font-family: "Fira Code";
                    }
                }
            }
        }
    }
}
