import { Palette } from "../theme/globals.slint";

export struct MapPoint {
    x: float,
    y: float,
    nazwa: string,
}

export component MapaKanwa inherits Rectangle {
    in property <[MapPoint]> map_points: [];
    in-out property <float> map_zoom: 1.0;
    in-out property <length> map_offset_x: 0px;
    in-out property <length> map_offset_y: 0px;
    horizontal-stretch: 1;
    background: Palette.background-light;
    border-radius: 4px;
    border-width: 1px;
    border-color: Palette.accent-success;
    clip: true;

    // Funkcja dostępna dla rodzica
    public function zoom_around_center(new_zoom: float) {
        if (new_zoom <= 0) {
            return;
        }
        let old_zoom = root.map_zoom;
        let old_w = flick.width;
        let old_h = flick.height;
        let old_offset_x = root.map_offset_x;
        let old_offset_y = root.map_offset_y;
        let visual_center_x = old_w / 2;
        let visual_center_y = old_h / 2;
        let old_center_inner_x = visual_center_x - old_offset_x;
        let old_center_inner_y = visual_center_y - old_offset_y;
        let s = new_zoom / old_zoom;
        let new_center_inner_x = old_center_inner_x * s;
        let new_center_inner_y = old_center_inner_y * s;
        root.map_zoom = new_zoom;
        root.map_offset_x = visual_center_x - new_center_inner_x;
        root.map_offset_y = visual_center_y - new_center_inner_y;
    }
    flick := Flickable {
        width: 100%;
        height: 100%;
        interactive: true;
        viewport-x <=> root.map_offset_x;
        viewport-y <=> root.map_offset_y;
        viewport-width: map_layer.width;
        viewport-height: map_layer.height;
        map_layer := Rectangle {
            width: flick.width * root.map_zoom;
            height: flick.height * root.map_zoom;
            for pt in root.map_points: Rectangle {
                x: pt.x * parent.width - 2px;
                y: pt.y * parent.height - 2px;
                width: 4px;
                height: 4px;
                background: #ff0055;
                border-radius: 2px;
            }
        }
    }

    // Miejsce na wstrzyknięcie elementów wierzchnich (np. kokpitu)
    @children
}
