import { Palette } from "../theme/globals.slint";
import { ResizeBorders } from "resize-borders.slint";

export component CustomBtn {
    in property <string> text;
    in property <bool> enabled: true;
    in property <bool> primary: false;
    in property <brush> custom-hover-bg: Palette.hover-background;
    callback clicked;
    Rectangle {
        background: root.primary ? #00a2ff : (ta.has-hover ? root.custom-hover-bg : (root.enabled ? Palette.background-light : Palette.background));
        border-width: 1px;
        border-color: Palette.border;
        border-radius: 4px;
        height: 100%;
        width: 100%;
        Text {
            text: root.text;
            color: !root.enabled ? Palette.text-secondary : (root.primary ? white : Palette.text-primary);
            font-weight: 700;
            vertical-alignment: center;
            horizontal-alignment: center;
        }

        ta := TouchArea {
            enabled: root.enabled;
            clicked => {
                root.clicked();
            }
            mouse-cursor: self.has-hover ? pointer : default;
        }
    }
}

export global WindowCtrl {
    callback window_quit();
    callback window_minimize();
    callback window_move(length, length);
    callback window_resize(string);
}

export component WindowShell inherits Window {
    no-frame: true;
    background: transparent;
    min-width: 50px;
    min-height: 200px;
    in property <string> window-title: "TYTUŁ OKNA";
    // Definiujemy callbacki RAZ
    //callback window_quit();
    //callback window_minimize();
    //callback window_move(length, length);
    //callback window_resize(string);
    Rectangle {
        width: 100%;
        height: 100%;
        background: Palette.window-backgr-box;
        border-radius: 12px;
        border-width: 2px;
        border-color: Palette.window-border-box;
        clip: true;
        VerticalLayout {
            Rectangle {
                height: 50px;
                background: Palette.window-backgr-bar;
                TouchArea {
                    width: 100%;
                    height: 100%;
                    pointer-event(event) => {
                        if (event.kind == PointerEventKind.down && event.button == PointerEventButton.left) {
                            WindowCtrl.window_move(0px, 0px);
                        }
                    }
                }

                HorizontalLayout {
                    padding-left: 15px;
                    padding-right: 15px;
                    spacing: 10px;
                    Text {
                        text: root.window-title;
                        color: Palette.window-text-main;
                        vertical-alignment: center;
                        font-weight: 700;
                    }

                    Rectangle {
                        horizontal-stretch: 1;
                    }

                    CustomBtn {
                        text: "X";
                        //✕
                        width: 35px;
                        height: 35px;
                        custom-hover-bg: #ff000033;
                        clicked => {
                            WindowCtrl.window_quit();
                        }
                    }

                    CustomBtn {
                        text: "—";
                        width: 35px;
                        height: 35px;
                        custom-hover-bg: #00a2ff33;
                        clicked => {
                            WindowCtrl.window_minimize();
                        }
                    }

                    CustomBtn {
                        text: Palette.is-dark ? "☀️" : "🌙";
                        width: 40px;
                        height: 35px;
                        clicked => {
                            Palette.is-dark = !Palette.is-dark;
                        }
                    }
                }
            }

            Rectangle {
                vertical-stretch: 1;
                @children
            }
        }

        ResizeBorders {
            resize(dir) => {
                WindowCtrl.window_resize(dir);
            }
        }
    }
}
